Repository Jay13Jeong/PinguPong, pull requests merged in 2023-02, with the labels that each got.

#33 Feature/jeyoon
  pong_front/src/App.tsx
  pong_front/src/Routing.tsx
  pong_front/src/assets/Pingu3D.png
  pong_front/src/assets/logo.png
  pong_front/src/components/Lobby.tsx
  pong_front/src/components/TopMenuBar.tsx
  pong_front/src/components/auth/Login.tsx
  pong_front/src/components/game/GamePlayRoom.tsx
  pong_front/src/components/game/GameWatchList.tsx
  pong_front/src/components/modal/CreateChatModal.tsx
  pong_front/src/components/modal/DMModal.tsx
  pong_front/src/components/modal/FriendModal.tsx
  pong_front/src/components/modal/Modal.tsx
  pong_front/src/components/modal/ModalBase.tsx
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.scss
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/util/card/CardList.scss
  pong_front/src/components/util/card/ChatCardButton.tsx
  pong_front/src/components/util/card/ChatCardButtonList.tsx
  pong_front/src/pages/chat/ChatLobby.tsx
  pong_front/src/states/recoilModalState.ts
  pong_front/src/styles/Modal.ts
Labels: enhancement

#40 test : profile api connect
  pong_front/public/default.jpeg
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/profile/User.d.ts
  pong_nestjs/src/modules/auth/second-auth/second-auth.controller.ts
  pong_nestjs/src/modules/users/user.entity.ts
  pong_nestjs/src/modules/users/users.controller.ts
  pong_nestjs/src/modules/users/users.service.ts
Labels: enhancement

#41 Feature/jjeong
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_nestjs/src/app.module.ts
  pong_nestjs/src/modules/chat/chat.entity.ts
  pong_nestjs/src/modules/chat/msg.entity.ts
  pong_nestjs/src/modules/friend/friend.controller.ts
  pong_nestjs/src/modules/game/game.entity.ts
  pong_nestjs/src/modules/users/user.entity.ts
  pong_nestjs/src/modules/users/users.controller.ts
Labels: enhancement

#45 Feature/cheolee
  pong_nestjs/src/modules/game/game.service.ts
  pong_nestjs/src/modules/game/pingpong.gateway.ts
Labels: enhancement

#47 Feature/jjeong
  pong_front/src/components/modal/FriendModal.tsx
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/profile/User.d.ts
  pong_nestjs/src/modules/friend/friend.controller.ts
  pong_nestjs/src/modules/friend/friend.service.ts
Labels: enhancement

#53 fix : block api
  pong_front/src/App.css
  pong_front/src/assets/pingu-lollipop.gif
  pong_front/src/components/Lobby.tsx
  pong_front/src/components/TopMenuBar.scss
  pong_front/src/components/auth/Login.scss
  pong_front/src/components/auth/Login.tsx
  pong_front/src/components/modal/FriendModal.tsx
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_nestjs/src/modules/friend/friend.controller.ts
  pong_nestjs/src/modules/friend/friend.service.ts
Labels: bug, enhancement

#54 fix : 2fa font color
  pong_front/src/App.css
  pong_front/src/assets/pinga-door.gif
  pong_front/src/components/auth/FA2.tsx
  pong_front/src/components/auth/Login.scss
Labels: enhancement

#61 feat: 채팅 테스트파일 수정, 핑퐁 관전기능 완료및 테스트 파일 수정
  pong_front/public/exSocketio targetid.html
  pong_front/public/exSocketio temp.html
  pong_front/public/exSocketio.html
  pong_front/public/pingtest.html
  pong_nestjs/src/modules/game/game.service.ts
  pong_nestjs/src/modules/socket/socket.gateway.ts
Labels: enhancement

#62 feat : add init profile page
  pong_front/src/Routing.tsx
  pong_front/src/components/Lobby.tsx
  pong_front/src/components/auth/Login.scss
  pong_front/src/components/profile/Init.tsx
  pong_front/src/components/profile/Modal.tsx
  pong_front/src/pages/profile/ProfileInitPage.tsx
  pong_front/src/pages/profile/ProfileModal.tsx
  pong_nestjs/src/modules/auth/auth.service.ts
  pong_nestjs/src/modules/users/users.controller.ts
Labels: enhancement

#63 feat : add dynamic host
  docker-compose.yaml
  pong_front/Dockerfile
  pong_front/src/App.tsx
  pong_front/src/components/Lobby.tsx
  pong_front/src/components/TopMenuBar.tsx
  pong_front/src/components/auth/FA2.tsx
  pong_front/src/components/auth/Login.tsx
  pong_front/src/components/game/GameWatchRoom.tsx
  pong_front/src/components/game/MatchMake.tsx
  pong_front/src/components/modal/BlockModal.tsx
  pong_front/src/components/modal/ChatMenuModal.tsx
  pong_front/src/components/modal/FriendModal.tsx
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/profile/Init.tsx
  pong_front/src/components/util/card/ChatCardButtonList.tsx
  pong_front/src/pages/chat/ChatRoom.tsx
  pong_front/src/states/contextSocket.ts
  pong_front/src/util/configData.ts
  pong_front/src/util/useUser.ts
  pong_nestjs/src/main.ts
  pong_nestjs/src/modules/auth/auth.controller.ts
Labels: bug, enhancement

#64 feat : apply hash pw to db
  pong_front/src/components/modal/ProfileModal.tsx
  pong_nestjs/src/modules/auth/guard/jwt.guard.ts
  pong_nestjs/src/modules/auth/guard/jwt.strategy.ts
  pong_nestjs/src/modules/auth/second-auth/second-auth.controller.ts
Labels: enhancement

#67 Feature/jjeong
  pong_front/src/components/auth/FA2.tsx
  pong_front/src/components/auth/Login.scss
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/profile/Init.tsx
  pong_nestjs/avatars/default.jpeg
  pong_nestjs/package.json
  pong_nestjs/src/modules/users/users.controller.ts
  pong_nestjs/src/modules/users/users.module.ts
  pong_nestjs/src/modules/users/users.service.ts
  pong_nestjs/test/app.e2e-spec.ts
  pong_nestjs/test/jest-e2e.json
Labels: enhancement

#68 feat : avatar upload func
  pong_front/src/App.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_nestjs/package.json
  pong_nestjs/src/modules/users/users.controller.ts
  pong_nestjs/src/modules/users/users.module.ts
Labels: enhancement

#79 Feature/jjeong
  pong_front/src/components/modal/FriendModal.tsx
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/util/card/GameRecordList.tsx
  pong_nestjs/src/modules/game/game.controller.ts
  pong_nestjs/src/modules/game/game.dto.ts
  pong_nestjs/src/modules/game/game.entity.ts
  pong_nestjs/src/modules/game/game.module.ts
  pong_nestjs/src/modules/game/game.service.ts
  pong_nestjs/src/modules/socket/socket.gateway.ts
  pong_nestjs/src/modules/socket/socket.module.ts
  pong_nestjs/src/modules/users/users.controller.ts
Labels: enhancement

#80 fix : syntax err
  pong_nestjs/src/modules/socket/socket.gateway.ts
  pong_nestjs/src/modules/socket/socket.module.ts
Labels: bug

#85 Chat 세부 기능들 연결
  pong_front/src/components/game/GameWatchList.tsx
  pong_front/src/components/game/MatchMake.tsx
  pong_front/src/components/modal/BlockModal.tsx
  pong_front/src/components/modal/ChangeChatPwModal.tsx
  pong_front/src/components/modal/ChatMenuModal.tsx
  pong_front/src/components/modal/CreateChatModal.tsx
  pong_front/src/components/modal/DMModal.tsx
  pong_front/src/components/modal/FriendModal.tsx
  pong_front/src/components/modal/SecretChatModal.tsx
  pong_front/src/components/util/card/ChatCardButton.tsx
  pong_front/src/pages/chat/ChatLobby.tsx
  pong_front/src/pages/chat/ChatRoom.tsx
  pong_front/src/pages/game/GameLobbyPage.tsx
  pong_nestjs/src/modules/chat/chatClass.ts
Labels: enhancement

#86 feat : background component
  pong_front/public/logo192.png
  pong_front/public/logo512.png
  pong_front/src/assets/pingu1.gif
  pong_front/src/assets/pingu2.gif
  pong_front/src/assets/pingu3.gif
  pong_front/src/assets/pingu4.gif
  pong_front/src/assets/pingu5.gif
  pong_front/src/assets/pingu6.gif
  pong_front/src/assets/pingu7.gif
  pong_front/src/assets/pingu8.gif
  pong_front/src/components/Lobby.tsx
  pong_front/src/components/auth/Login.tsx
  pong_front/src/components/util/BackGroundPingu.tsx
Labels: enhancement

#88 feat:유저상태 확인 온라인 추가
  pong_nestjs/src/modules/socket/socket.gateway.ts
Labels: bug, enhancement

#90 Feature/jjeong
  pong_front/src/components/modal/ProfileEditModal.tsx
  pong_front/src/components/modal/ProfileModal.tsx
  pong_front/src/components/util/card/UserCardButton.tsx
  pong_nestjs/src/modules/socket/socket.gateway.ts
Labels: enhancement

#92 로그인시에만 세부 페이지로 라우팅되도록 수정
  pong_front/src/Routing.tsx
  pong_front/src/index.tsx
  pong_front/src/pages/NotFound.tsx
  pong_front/src/states/recoilUserState.ts
  pong_front/src/util/useCheckLogin.ts
  pong_front/src/util/useGetData.ts
Labels: enhancement

#100 fix : compile err
  pong_front/src/pages/game/GamePlayRoomPage.tsx
Labels: bug

#102 feat : :art: change cursor
  pong_front/src/App.tsx
  pong_front/src/assets/cursorPingu.png
  pong_front/src/components/auth/FA2.tsx
  pong_front/src/components/auth/Login.scss
  pong_front/src/components/util/Cursor.tsx
Labels: enhancement

#114 Feature/jjeong
  pong_front/src/components/chat/modal/ChatMenuModal.tsx
  pong_front/src/components/layout/MainLayout.tsx
  pong_front/src/components/lobby/LobbyModal.tsx
  pong_front/src/components/lobby/modal/FriendModal.tsx
Labels: enhancement
